server:
  port: 8082
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://jelani.db.elephantsql.com:5432/twaajlsg?socketTimeout=3
    username: twaajlsg
    password: 8cP7fgym_8tqyDQs3LYApGJeLTSO4w5n
    driverClassName: org.postgresql.Driver